HIMS.Web/Controllers/LayoutController.cs
// =============================
// Email: info@blackbrackets.com
// www.blackbrackets.com
// =============================
using HIMS.Service.PageServices;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HIMS.Web.Controllers
{
	public class LayoutController : BaseController
	{
		private readonly IPageService pageService;
		public LayoutController(IPageService _pageService)
		{
			pageService = _pageService;
		}
		[ChildActionOnly]
		public PartialViewResult TopBar()
		{
			return PartialView("_TopBar");

		}

		[ChildActionOnly]
		public PartialViewResult SideBarNav(string activeMenu = "")
		{
			var item =  pageService.GetPageListAsync();
			return PartialView("_LeftSideBar", item);
		}
	}
}

HIMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>HIMS</title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    @*<script src="~/Scripts/Custom/webfont.js"></script>*@
    <script>
        WebFont.load({
            google: { "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Web font -->
    <!--begin::Global Theme Styles -->
    @Styles.Render("~/Bundles/Global-Css")
    <!--end::Global Theme Styles -->
    <!--begin::Page Level Theme Styles -->
    @RenderSection("Style", required: false)
    <!--end::Page Level Theme Styles -->
    @*<link rel="shortcut icon" href="~/Theme/assets/demo/default/media/img/logo/favicon.png" />*@
</head>
<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
    <!-- begin:: Page -->
    <div class="m-grid m-grid--hor m-grid--root m-page">
        <!-- BEGIN: Header -->
        <header id="m_header" class="m-grid__item    m-header " m-minimize-offset="200" m-minimize-mobile-offset="200">
            <div class="m-container m-container--fluid m-container--full-height">
                <div class="m-stack m-stack--ver m-stack--desktop">
                    <!-- BEGIN: Brand -->
                    <div class="m-stack__item m-brand  m-brand--skin-dark ">
                        <div class="m-stack m-stack--ver m-stack--general">
                            <div class="m-stack__item m-stack__item--middle m-brand__logo">
                                <h1 style="color:white;text-align:center">HIMS</h1>
                            </div>
                            <div class="m-stack__item m-stack__item--middle m-brand__tools">
                                <!-- BEGIN: Left Aside Minimize Toggle -->
                                <a href="javascript:;" id="m_aside_left_minimize_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-desktop-inline-block  ">
                                    <span></span>
                                </a>
                                <!-- END -->
                                <!-- BEGIN: Responsive Aside Left Menu Toggler -->
                                <a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
                                    <span></span>
                                </a>
                                <!-- END -->
                                <!-- BEGIN: Responsive Header Menu Toggler -->
                                <a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
                                    <span></span>
                                </a>
                                <!-- BEGIN: Topbar Toggler -->
                            </div>
                        </div>
                    </div>

                    <!-- END: Brand -->
                    <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
                        <!-- BEGIN: Horizontal Menu -->
                        <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-dark " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>

                        <!-- END: Horizontal Menu -->
                        <!-- BEGIN: Topbar -->
                        @Html.Action("Topbar", "Layout")
                        <!-- END: Topbar -->
                    </div>
                </div>
            </div>
        </header>

        <!-- END: Header -->
        <!-- begin::Body -->
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
            <!-- BEGIN: Left Aside -->
            @Html.Action("SideBarNav", "Layout")
            <!-- END: Left Aside -->
            <!-- BEGIN: Body -->
            @RenderBody()
            <!-- END: Body-->
        </div>

        <!-- end:: Body -->
        <!-- begin::Footer -->
        <footer class="m-grid__item m-footer ">
            <div class="m-container m-container--fluid m-container--full-height m-page__container">
                <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
                    <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
                        <span class="m-footer__copyright">
                            @DateTime.UtcNow.Year &copy; HIMS, All rights are reserved@*. Developed By <a href="http://www.blackbrackets.com" target="_blank">BlackBrackets</a>*@
                        </span>
                    </div>
                </div>
            </div>
        </footer>

        <!-- end::Footer -->
    </div>

    <!-- end:: Page -->
    <!-- begin::Scroll Top -->
    <div id="m_scroll_top" class="m-scroll-top">
        <i class="la la-arrow-up"></i>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/Bundles/Global-Js")
    <!--end::Global Theme Bundle -->
    <!--begin::Page Scripts -->
    @*<script src="assets/app/js/dashboard.js" type="text/javascript"></script>*@
    @RenderSection("Scripts", required: false)
    <script type="text/javascript" src="~/Theme/assets/demo/default/custom/components/base/sweetalert2.js"></script>
    @*<script src="/Scripts/jquery.signalR-2.4.0.min.js"></script>*@
    <!--Reference the autogenerated SignalR hub script. -->
    @*<script src="/signalr/hubs" type="text/javascript"></script>*@
    <!--end::Page Scripts -->

</body>
</html>