HIMS.Web/Controllers/ReferanceController.cs
// =============================
// Email: info@blackbrackets.com
// www.blackbrackets.com
// =============================
using HIMS.Service.Constant;
using HIMS.Service.Model;
using HIMS.Service.ReferanceServices;
using HIMS.Service.ReferanceServices.Dto;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HIMS.Web.Controllers
{
	public class ReferanceController : BaseController
	{
		private readonly IReferanceMasterService _referanceService;
		private readonly IConstantService _constantService;

		public ReferanceController(IReferanceMasterService referanceService, IConstantService constantService)
		{
			_referanceService = referanceService;
			_constantService = constantService;
		}

		#region Bind Dropdowns
		public void BindAllDropdowns()
		{
			BindStatus();
			BindReferenceType();
			BindBloodGroup();
			BindCity();
			BindCountry();
			BindGender();
			BindSpeciality();
			BindState();
		}
		private void BindStatus()
		{
			var data = _constantService.GetDropDownListFromTable("recstatus");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.Status = _reftype;
			}
		}

		private void BindReferenceType()
		{
			var data = _constantService.GetDropDownListFromTable("reftype");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.ReferenceType = _reftype;
			}
		}

		private void BindBloodGroup()
		{
			var data = _constantService.GetDropDownListFromTable("bloodgroup");
			if (data != null)
			{ 
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
 				ViewBag.BloodGroup = _reftype;
			}
		}

		private void BindCountry()
		{
			var data = _constantService.GetCountryList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Countryname");
				ViewBag.Country = _reftype;
			}
		}

		private void BindState()
		{
			var data = _constantService.GetStateList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Statename");
				ViewBag.State = _reftype;
			}
		}

		private void BindCity()
		{
			var data = _constantService.GetCityList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Cityname");
				ViewBag.City = _reftype;
			}
		}

		private void BindGender()
		{
			var data = _constantService.GetDropDownListFromTable("gender");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.Gender = _reftype;
			}
		}

		private void BindSpeciality()
		{
			var data = _constantService.GetSpecialityList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "SpecialityName");
				ViewBag.Speciality = _reftype;
			}
		}
		#endregion

		// GET: Country
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Index(DataTableAjaxPostModel<ReferanceDtoForList> modelDT)
		{
			try
			{
				var designationList = await _referanceService.GetAll(modelDT);
				return Json(new { data = designationList.Item1, draw = Request["draw"], recordsTotal = designationList.Item2, recordsFiltered = designationList.Item3 }, JsonRequestBehavior.AllowGet);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpGet]
		public ActionResult Create()
		{
			BindAllDropdowns();
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Create(ReferanceDto referanceDto)
		{
			try
			{
				if (ModelState.IsValid)
				{
					if (referanceDto.RefSignFile != null)
					{
						using (Stream inputStream = referanceDto.RefSignFile.InputStream)
						{
							MemoryStream memoryStream = inputStream as MemoryStream;
							if (memoryStream == null)
							{
								memoryStream = new MemoryStream();
								inputStream.CopyTo(memoryStream);
							}
							referanceDto.RefSign = memoryStream.ToArray();
						}
					}
					await _referanceService.CreateAsync(referanceDto);
					return RedirectToAction("Index");
				}
				else
				{
					BindAllDropdowns();
					return View("Create", referanceDto);
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpGet]
		public async Task<ActionResult> Edit(long Id)
		{
			try
			{
				BindAllDropdowns();
				var _country = await _referanceService.GetById(Id);
				return View(_country);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpPost]
		public async Task<ActionResult> Edit(long Id, ReferanceDto referanceDto)
		{
			try
			{
				if (ModelState.IsValid)
				{
					if (referanceDto.RefSignFile != null)
					{
						using (Stream inputStream = referanceDto.RefSignFile.InputStream)
						{
							MemoryStream memoryStream = inputStream as MemoryStream;
							if (memoryStream == null)
							{
								memoryStream = new MemoryStream();
								inputStream.CopyTo(memoryStream);
							}
							referanceDto.RefSign = memoryStream.ToArray();
						}
					}
					await _referanceService.Update(referanceDto);
					return RedirectToAction("Index");
				}
				else
				{
					BindAllDropdowns();
					return View("Edit", referanceDto);
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		public async Task<ActionResult> Delete(long Id)
		{
			try
			{
				await _referanceService.Delete(Id);
				return Json(true, JsonRequestBehavior.AllowGet);

			}
			catch (Exception ex)
			{
				throw ex;
			}
		}
	}
}

HIMS.Web/Controllers/TieUpController.cs
// =============================
// Email: info@blackbrackets.com
// www.blackbrackets.com
// =============================
using HIMS.Service.Constant;
using HIMS.Service.Model;
using HIMS.Service.TieupServices;
using HIMS.Service.TieupServices.Dto;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HIMS.Web.Controllers
{
	public class TieUpController : BaseController
	{
		private readonly ITieupMasterService _tieupMasterService;
		private readonly IConstantService _constantService;

		public TieUpController(ITieupMasterService referanceService, IConstantService constantService)
		{
			_tieupMasterService = referanceService;
			_constantService = constantService;
		}

		#region Bind Dropdowns

		public void BindAllDropdowns()
		{
			BindStatus();
			BindReferenceType();
			BindBloodGroup();
			BindCity();
			BindCountry();
			BindGender();
			BindSpeciality();
			BindState();
		}
		private void BindStatus()
		{
			var data = _constantService.GetDropDownListFromTable("recstatus");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.Status = _reftype;
			}
		}

		private void BindReferenceType()
		{
			var data = _constantService.GetDropDownListFromTable("reftype");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.ReferenceType = _reftype;
			}
		}

		private void BindBloodGroup()
		{
			var data = _constantService.GetDropDownListFromTable("bloodgroup");
			if (data != null)
			{ 
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
 				ViewBag.BloodGroup = _reftype;
			}
		}

		private void BindCountry()
		{
			var data = _constantService.GetCountryList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Countryname");
				ViewBag.Country = _reftype;
			}
		}

		private void BindState()
		{
			var data = _constantService.GetStateList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Statename");
				ViewBag.State = _reftype;
			}
		}

		private void BindCity()
		{
			var data = _constantService.GetCityList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "Cityname");
				ViewBag.City = _reftype;
			}
		}

		private void BindGender()
		{
			var data = _constantService.GetDropDownListFromTable("gender");
			if (data != null)
			{
				IEnumerable<SelectListItem> _reftype = data.Select(x => new SelectListItem { Value = x, Text = x });
				ViewBag.Gender = _reftype;
			}
		}

		private void BindSpeciality()
		{
			var data = _constantService.GetSpecialityList();
			if (data != null)
			{
				var _reftype = new SelectList(data.ToList(), "Id", "SpecialityName");
				ViewBag.Speciality = _reftype;
			}
		}
		#endregion

		// GET: Country
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Index(DataTableAjaxPostModel<TieupDto> modelDT)
		{
			try
			{
				var designationList = await _tieupMasterService.GetAll(modelDT);
				return Json(new { data = designationList.Item1, draw = Request["draw"], recordsTotal = designationList.Item2, recordsFiltered = designationList.Item3 }, JsonRequestBehavior.AllowGet);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpGet]
		public ActionResult Create()
		{
			BindAllDropdowns();
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Create(TieupDto referanceDto)
		{
			try
			{
				if (ModelState.IsValid)
				{ 
					await _tieupMasterService.CreateAsync(referanceDto);
					return RedirectToAction("Index");
				}
				else
				{
					BindAllDropdowns();
					return View("Create", referanceDto);
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpGet]
		public async Task<ActionResult> Edit(long Id)
		{
			try
			{
				BindAllDropdowns();
				var _country = await _tieupMasterService.GetById(Id);
				return View(_country);
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpPost]
		public async Task<ActionResult> Edit(long Id, TieupDto referanceDto)
		{
			try
			{
				if (ModelState.IsValid)
				{ 
					await _tieupMasterService.Update(referanceDto);
					return RedirectToAction("Index");
				}
				else
				{
					BindAllDropdowns();
					return View("Edit", referanceDto);
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		public async Task<ActionResult> Delete(long Id)
		{
			try
			{
				await _tieupMasterService.Delete(Id);
				return Json(true, JsonRequestBehavior.AllowGet);

			}
			catch (Exception ex)
			{
				throw ex;
			}
		}
	}
}

HIMS.Web/Views/TieUp/Create.cshtml
@model HIMS.Service.TieupServices.Dto.TieupDto
@{
    ViewBag.Title = "Create";
}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">TieUp Master</h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="@Url.Action("Index", "Home")" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="@Url.Action("Index", "TieUp")" class="m-nav__link">
                            <span class="m-nav__link-text">TieUp Master</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->

    @using (Html.BeginForm("Create", "TieUp", FormMethod.Post, new { @class = "m-form m-form--fit m--margin-bottom-20", role = "form", @id = "CreateReferance", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Add TieUp
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body"> 

                    @Html.HiddenFor(m => m.Id)
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Tieupcode)<span class="m--margin-left-5 m--icon-font-size-sm2 text-danger">*</span>
                            @Html.EditorFor(model => model.Tieupcode, new { htmlAttributes = new { @class = "form-control m-input numberonly", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Tieupcode, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.Compname)<span class="m--margin-left-5 m--icon-font-size-sm2 text-danger">*</span>
                            @Html.EditorFor(model => model.Compname, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Compname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address1)
                            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address2)
                            @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address3)
                            @Html.EditorFor(model => model.Address3, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Cityid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Cityid, ViewBag.City as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Stateid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Stateid, ViewBag.State as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Countryid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Countryid, ViewBag.Country as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Contact)
                            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Mobileno)
                            @Html.EditorFor(model => model.Mobileno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Emailid)
                            @Html.EditorFor(model => model.Emailid, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Website)
                            @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Gstno)
                            @Html.EditorFor(model => model.Gstno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Panno)
                            @Html.EditorFor(model => model.Panno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Contpername)
                            @Html.EditorFor(model => model.Contpername, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Designation)
                            @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.Label("Status")
                            @Html.DropDownListFor(model => model.Recstatus, ViewBag.Status as IEnumerable<SelectListItem>, new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4" })
                        </div>
                        <div class="col-lg"></div>
                    </div>
                    <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                        <div class="m-form__actions m-form__group">
                            <div class="row">
                                <div class="col-lg-6">
                                </div>
                                <div class="col-lg-6 m--align-right">
                                    <input type="button" value="Cancel" class="btn btn-default" onclick="window.location='@Url.Action("Index","TieUp")'" />
                                    <input id="btnSubmit" type="submit" value="Save" class="btn btn-primary m--margin-10" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/TieUp/Create.js")
}

HIMS.Web/Views/TieUp/Edit.cshtml
@model HIMS.Service.TieupServices.Dto.TieupDto
@{
    ViewBag.Title = "Edit";

}
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">TieUp Master</h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="@Url.Action("Index", "Home")" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">-</li>
                    <li class="m-nav__item">
                        <a href="@Url.Action("Index", "Referance")" class="m-nav__link">
                            <span class="m-nav__link-text">TieUp Master</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Subheader -->

    @using (Html.BeginForm("Edit", "Tieup", FormMethod.Post, new { @class = "m-form m-form--fit m--margin-bottom-20", role = "form", @id = "CreateReferance", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Update TieUp
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    @Html.HiddenFor(m => m.Id)
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Tieupcode)<span class="m--margin-left-5 m--icon-font-size-sm2 text-danger">*</span>
                            @Html.EditorFor(model => model.Tieupcode, new { htmlAttributes = new { @class = "form-control m-input numberonly", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Tieupcode, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-6">
                            @Html.LabelFor(model => model.Compname)<span class="m--margin-left-5 m--icon-font-size-sm2 text-danger">*</span>
                            @Html.EditorFor(model => model.Compname, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Compname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address1)
                            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address2)
                            @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Address3)
                            @Html.EditorFor(model => model.Address3, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Cityid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Cityid, ViewBag.City as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Stateid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Stateid, ViewBag.State as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Countryid)&nbsp;&nbsp;<a class="btn btn-group"><i class="fa fa-plus"></i></a>
                            @Html.DropDownListFor(model => model.Countryid, ViewBag.Country as SelectList, "Select", new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4", data_live_search = true })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Contact)
                            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Mobileno)
                            @Html.EditorFor(model => model.Mobileno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Emailid)
                            @Html.EditorFor(model => model.Emailid, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Website)
                            @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Gstno)
                            @Html.EditorFor(model => model.Gstno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Panno)
                            @Html.EditorFor(model => model.Panno, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Contpername)
                            @Html.EditorFor(model => model.Contpername, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                        <div class="col-lg">
                            @Html.LabelFor(model => model.Designation)
                            @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control m-input", @autocomplete = "off" } })
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg">
                            @Html.Label("Status")
                            @Html.DropDownListFor(model => model.Recstatus, ViewBag.Status as IEnumerable<SelectListItem>, new { @class = "form-control m-bootstrap-select m_selectpicker", data_size = "4" })
                        </div>
                        <div class="col-lg"></div>
                    </div>
                    <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                        <div class="m-form__actions m-form__group">
                            <div class="row">
                                <div class="col-lg-6">
                                </div>
                                <div class="col-lg-6 m--align-right">
                                    <input type="button" value="Cancel" class="btn btn-default" onclick="window.location='@Url.Action("Index","Referance")'" />
                                    <input id="btnSubmit" type="submit" value="Save" class="btn btn-primary m--margin-10" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/TieUp/Create.js")
}